apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: owncloud

patches:
  - target:
      kind: Ingress
      name: owncloud-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: prod.lesaiglesbraves.online
      - op: replace
        path: /spec/rules/0/host
        value: prod.lesaiglesbraves.online
  
  - target:
      kind: SecretProviderClass
      name: ocis-keyvault-certs
    patch: |-
      - op: replace
        path: /spec/parameters/keyvaultName
        value: owncloudkvprod
      - op: replace
        path: /spec/parameters/tenantId
        value: adb4b793-234b-4db7-8a27-1eb5a79637e2
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: 14d82c77-2dd4-4932-84e4-51ed88896ccc

configMapGenerator:
  - name: ocis-config
    behavior: merge
    literals:
      - ocis-url=https://prod.lesaiglesbraves.online

secretGenerator:
  - name: ocis-secret
    behavior: merge
    literals:
      - admin-password=__ADMIN_PASSWORD__
      - admin-email=stephane.nzali@gmail.com
