# Configuration pour récupérer les certificats depuis Azure Key Vault
# Les certificats doivent être préalablement créés avec manage-certificates.ps1
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ocis-keyvault-certs
  namespace: owncloud
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""  # Sera renseigné par Kustomize selon l'environnement
    keyvaultName: ""  # Sera renseigné par Kustomize selon l'environnement
    cloudName: ""
    objects: |
      array:
        - |
          objectName: ocis-tls-cert
          objectType: cert
          objectAlias: ocis-tls-cert
        - |
          objectName: ocis-tls-key
          objectType: secret
          objectAlias: ocis-tls-key
    tenantId: ""  # Sera renseigné par Kustomize
  secretObjects:
  - secretName: ocis-tls
    type: kubernetes.io/tls
    data:
    - objectName: ocis-tls-cert
      key: tls.crt
    - objectName: ocis-tls-key
      key: tls.key
