apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: owncloud-ingress
  namespace: owncloud
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - KEYCLOAK_HOSTNAME
    - OCIS_HOSTNAME
    secretName: owncloud-tls
  rules:
  - host: KEYCLOAK_HOSTNAME
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080
  - host: OCIS_HOSTNAME
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ocis
            port:
              number: 9200
