apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keycloak-tls
  namespace: owncloud
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: KEYVAULT_NAME
    cloudName: ""
    objects: |
      array:
        - |
          objectName: keycloak-tls-cert
          objectType: cert
          objectVersion: ""
        - |
          objectName: keycloak-tls-key
          objectType: secret
          objectVersion: ""
    tenantId: TENANT_ID
  secretObjects:
  - secretName: keycloak-tls
    type: kubernetes.io/tls
    data:
    - objectName: keycloak-tls-cert
      key: tls.crt
    - objectName: keycloak-tls-key
      key: tls.key
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ocis-keyvault-certs
  namespace: owncloud
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: KEYVAULT_NAME
    cloudName: ""
    objects: |
      array:
        - |
          objectName: ocis-tls-cert
          objectType: cert
          objectVersion: ""
        - |
          objectName: ocis-tls-key
          objectType: secret
          objectVersion: ""
    tenantId: TENANT_ID
  secretObjects:
  - secretName: ocis-tls
    type: kubernetes.io/tls
    data:
    - objectName: ocis-tls-cert
      key: tls.crt
    - objectName: ocis-tls-key
      key: tls.key
