apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: owncloud

patches:
  - target:
      kind: Ingress
      name: owncloud-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev.lesaiglesbraves.online
      - op: replace
        path: /spec/rules/0/host
        value: dev.lesaiglesbraves.online
  
  - target:
      kind: SecretProviderClass
      name: ocis-keyvault-certs
    patch: |-
      - op: replace
        path: /spec/parameters/keyvaultName
        value: owncloudkvdev
      - op: replace
        path: /spec/parameters/tenantId
        value: TENANT_ID

configMapGenerator:
  - name: keycloak-config
    behavior: merge
    literals:
      - hostname=dev.lesaiglesbraves.online
      - db-host=owncloud-db-dev.postgres.database.azure.com
  
  - name: ocis-config
    behavior: merge
    literals:
      - ocis-url=https://dev.lesaiglesbraves.online
      - oidc-issuer=https://dev.lesaiglesbraves.online/auth/realms/owncloud
      - db-host=owncloud-db-dev.postgres.database.azure.com

secretGenerator:
  - name: postgres-secret
    behavior: merge
    literals:
      - username=owncloudadmin
