apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: owncloud

patches:
  - target:
      kind: Ingress
      name: owncloud-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev.lesaiglesbraves.online
      - op: replace
        path: /spec/rules/0/host
        value: dev.lesaiglesbraves.online
  
  - target:
      kind: SecretProviderClass
      name: ocis-keyvault-certs
    patch: |-
      - op: replace
        path: /spec/parameters/keyvaultName
        value: owncloudkvdev
      - op: replace
        path: /spec/parameters/tenantId
        value: adb4b793-234b-4db7-8a27-1eb5a79637e2
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: 15e0ba3e-2f37-4612-985f-fd8525b62b83

configMapGenerator:
  - name: ocis-config
    behavior: merge
    literals:
      - ocis-url=https://dev.lesaiglesbraves.online

secretGenerator:
  - name: ocis-secret
    behavior: merge
    literals:
      - admin-password=5T3phane
